version: '3'
services: 
  backend:
    build:
      context:  ./ib-visual-backend
      dockerfile: Dockerfile
    image: hadrianl/ib-client_backend:${TAG}
    ports: 
      - 6789:6789
    env_file:
      - ib.env
    restart: on-failure
    command: python ./backend.py 
  data_recorder:
    build:
      context:  ./ib-visual-backend
      dockerfile: Dockerfile
    image: hadrianl/ib-client_backend:${TAG}
    environment:
      - RICURL=https://www.hsi.com.hk/HSI-Net/HSI-Net?cmd=nxgenindex&index=00001
    restart: on-failure
    depends_on:
      - influxdb
    command: python ./record_index_contribution.py
  frontend:
    build:
      context:  ./ib-visual-frontend
      dockerfile: Dockerfile
    image: hadrianl/ib-client_frontend:${TAG}
    ports:
      - 8080:8080
    env_file:
      - ib.env
    volumes: 
      - ./config:/app/config/
    restart: on-failure
  influxdb:
    image: influxdb
    ports: 
      - 8087:8086
    volumes:
      - influxdb:/var/lib/influxdb

volumes:
  influxdb: