version: '3'
services: 
  backend:
    build:
      context:  ./ib-visual-backend
      dockerfile: Dockerfile
    image: hadrianl/ib-client_backend:${TAG}
  extra_service:
    build:
      context:  ./ib-visual-backend
      dockerfile: Dockerfile
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
    image: hadrianl/ib-client_backend:${TAG}
  data_recorder:
    build:
      context:  ./ib-visual-backend
      dockerfile: Dockerfile
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
    image: hadrianl/ib-client_backend:${TAG}
  frontend:
    build:
      context:  ./ib-visual-frontend
      dockerfile: Dockerfile
    image: hadrianl/ib-client_frontend:${TAG}
